
import { Resource, Appointment, Driver, Trailer, TrailerTypeDefinition, Carrier } from './types';

// Mocks updated to include IDs and FacilityIDs (using 'FAC-MAIN' as placeholder for seeds)
export const MOCK_TRAILER_TYPES: TrailerTypeDefinition[] = [
  { id: 'tt-1', facilityId: 'FAC-MAIN', name: '20 FT Container', defaultDuration: 30, processTimePerPallet: 5 },
  { id: 'tt-2', facilityId: 'FAC-MAIN', name: '40 FT Container', defaultDuration: 60, processTimePerPallet: 5 },
  { id: 'tt-3', facilityId: 'FAC-MAIN', name: 'Single Axle Open', defaultDuration: 30, processTimePerPallet: 5 },
  { id: 'tt-4', facilityId: 'FAC-MAIN', name: 'Multi Axle Open', defaultDuration: 60, processTimePerPallet: 5 },
  { id: 'tt-5', facilityId: 'FAC-MAIN', name: 'Closed Body', defaultDuration: 20, processTimePerPallet: 5 },
  { id: 'tt-6', facilityId: 'FAC-MAIN', name: 'Low Bed / Hydraulic', defaultDuration: 40, processTimePerPallet: 5 },
  { id: 'tt-7', facilityId: 'FAC-MAIN', name: 'Tanker', defaultDuration: 90, processTimePerPallet: 100 },
  { id: 'tt-8', facilityId: 'FAC-MAIN', name: 'Light Commercial Vehicle', defaultDuration: 20, processTimePerPallet: 5 }
];

export const MOCK_CARRIERS: Carrier[] = [
  { id: 'CAR-001', facilityId: 'FAC-MAIN', name: 'Self Owned', contactEmail: 'logistics@company.com', contactPhone: '+91 98765 43210' },
  { id: 'CAR-002', facilityId: 'FAC-MAIN', name: 'Local Transport', contactEmail: 'dispatch@localtrans.com', contactPhone: '+91 98765 43211' }
];

export const MOCK_DOCKS: Resource[] = [];
export const MOCK_SLOTS: Resource[] = [];
export const MOCK_DRIVERS: Driver[] = [];
export const MOCK_TRAILERS: Trailer[] = [];
export const MOCK_APPOINTMENTS: Appointment[] = [];

// Shared ID constants for Permission Management
export const VIEW_IDS = {
  DASHBOARD: 'dashboard',
  DRIVER_BOARD: 'driver-board',
  CALENDAR: 'calendar',
  SCHEDULE: 'schedule',
  GUARD_GATE: 'guard-gate',
  GATEHOUSE: 'gatehouse',
  TRAILERS: 'trailers',
  RESOURCES: 'resources',
  CARRIERS: 'carriers',
  TRAILER_TYPES: 'trailer-types',
  DRIVERS: 'drivers',
  GATE_OUT: 'gateout',
  SETTINGS: 'settings',
  HELP: 'help',
  BILLING: 'billing',
  VISIBILITY: 'visibility',
  ACTIVITIES: 'activities',
  // Carrier Portal Specific Permissions
  CARRIER_DASHBOARD: 'carrier-dashboard',
  CARRIER_BOOKING: 'carrier-booking',
  CARRIER_APPOINTMENTS: 'carrier-appointments',
  CARRIER_FACILITIES: 'carrier-facilities'
};

export const NAV_ITEMS = [
  { id: VIEW_IDS.DRIVER_BOARD, label: 'Live Board', icon: 'MonitorPlay' },
  { id: VIEW_IDS.DASHBOARD, label: 'Command Center', icon: 'LayoutDashboard' },
  { id: VIEW_IDS.CALENDAR, label: 'Appt Calendar', icon: 'CalendarDays' },
  { id: VIEW_IDS.SCHEDULE, label: 'Appointments', icon: 'CalendarClock' },
  { id: VIEW_IDS.GUARD_GATE, label: 'Guard Gate', icon: 'Barrier' },
  { id: VIEW_IDS.GATEHOUSE, label: 'Check-in/Out', icon: 'ShieldCheck' },
  { id: VIEW_IDS.VISIBILITY, label: 'Yard Visibility', icon: 'Warehouse' },
  { id: VIEW_IDS.TRAILERS, label: 'Trailers', icon: 'Container' },
  { id: VIEW_IDS.ACTIVITIES, label: 'Activity Tracking', icon: 'History' },
  { id: VIEW_IDS.RESOURCES, label: 'Resources', icon: 'Box' },
  { id: VIEW_IDS.CARRIERS, label: 'Carriers', icon: 'Briefcase' },
  { id: VIEW_IDS.BILLING, label: 'Billing & Ledgers', icon: 'FileText' },
  { id: VIEW_IDS.TRAILER_TYPES, label: 'Trailer Types', icon: 'Truck' },
  { id: VIEW_IDS.DRIVERS, label: 'Drivers', icon: 'Users' },
  { id: VIEW_IDS.SETTINGS, label: 'Settings', icon: 'Settings' },
  { id: VIEW_IDS.HELP, label: 'Help & Docs', icon: 'BookOpen' },
];

export const CARRIER_NAV_ITEMS = [
  { id: VIEW_IDS.CARRIER_DASHBOARD, label: 'Carrier: Dashboard', icon: 'LayoutDashboard' },
  { id: VIEW_IDS.CARRIER_BOOKING, label: 'Carrier: Booking', icon: 'CalendarPlus' },
  { id: VIEW_IDS.CARRIER_APPOINTMENTS, label: 'Carrier: Appointments', icon: 'Calendar' },
  { id: VIEW_IDS.CARRIER_FACILITIES, label: 'Carrier: Facilities', icon: 'Building2' },
];

export const ALL_PERMISSIONS = [...NAV_ITEMS, ...CARRIER_NAV_ITEMS];

export const TRANSLATIONS = {
  en: {
    'nav.dashboard': 'Command Center',
    'nav.driver-board': 'Live Board',
    'nav.guard-gate': 'Guard Gate',
    'nav.calendar': 'Appt Calendar',
    'nav.schedule': 'Appointments',
    'nav.gatehouse': 'Check-in/Out',
    'nav.gateout': 'Check-out',
    'nav.resources': 'Resources',
    'nav.carriers': 'Carriers',
    'nav.trailers': 'Trailers',
    'nav.trailer-types': 'Trailer Types',
    'nav.drivers': 'Drivers',
    'nav.settings': 'Settings',
    'nav.help': 'Help & Docs',
    'nav.billing': 'Billing & Ledgers',
    'nav.visibility': 'Yard Visibility',

    'dash.title': 'SwiftYard Dashboard',
    'dash.subtitle': 'Real-time yard overview and resource tracking.',
    'dash.live': 'Live System',
    'kpi.pending': 'Pending Appts',
    'kpi.occupied': 'Occupied Docks',
    'kpi.yard': 'Trailers in Yard',
    'kpi.occupancy': 'Occupancy Rate',
    'dash.docks': 'Dock Doors',
    'dash.slots': 'Yard Slots',
    'dash.distribution': 'Dock Status Distribution',
    'dash.total': 'Total Docks',
    'dash.efficiency': 'Operational Efficiency',
    'dash.gateToDock': 'Average time from Gate to Dock',
    'dash.dockDwell': 'Average time at Dock',
    'dash.yardDwell': 'Average time at Yard',
    'dash.longStay': 'Long staying Trailers',
    'dash.mins': 'mins',
    'dash.alert': 'Alert',
    'dash.alertMsg': 'resources unavailable',
    'dash.congestion': 'Congestion Watch',

    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.dismiss': 'Dismiss',
    'common.phone': 'Phone',
    'common.carrier': 'Carrier',
    'common.driver': 'Driver',
    'common.status': 'Status',
    'common.trailer': 'Trailer',
    'common.type': 'Type',
    'common.time': 'Time',
    'common.actions': 'Actions',
    'common.id': 'ID',
    'common.duration': 'Duration',

    'schedule.title': 'Appointment Management',
    'schedule.subtitle': 'Appointments log and current status.',
    'schedule.new': 'New Appointment',
    'schedule.searchPlaceholder': 'Search by Driver, Trailer, or ID...',
    'schedule.emptyTitle': 'No appointments found',
    'schedule.emptyDesc': 'Adjust filters or create a new appointment.',

    'gate.title': 'Dock Door Check-In/Out',
    'gate.subtitle': 'Process arrivals and assign docks.',
    'gate.searchPlaceholder': 'Search scheduled arrivals...',
    'gate.arrivals': 'Scheduled Arrivals',
    'gate.pending': 'Pending',
    'gate.emptyArrivals': 'No scheduled arrivals found.',
    'gate.checkIn': 'Check In',
    'gate.inventory': 'Active Inventory',
    'gate.onsite': 'On Site',
    'gate.emptyInventory': 'No active trailers at dock.',
    'gate.checkOut': 'Check Out',
    'gate.modalTitle': 'Confirm Check-in',
    'gate.modalOriginal': 'Original Schedule',
    'gate.modalActual': 'Actual Arrival Time',
    'gate.modalAssign': 'Assign Location',
    'gate.autoAssign': 'Auto-Assign Best Available',
    'gate.modalAssignHint': 'Select a specific dock or let the system optimize placement.',
    'gate.confirmBtn': 'Confirm Check-in',
    'gate.successIn': 'Trailer checked into dock successfully.',
    'gate.successOut': 'Trailer checked out of dock successfully.',
    'gate.assignedLoc': 'Assigned Location',
    'gate.close': 'Close',

    'gateout.title': 'Dock Door Check-Out',
    'gateout.subtitle': 'Process vehicle departures.',
    'gateout.searchPlaceholder': 'Search active trailers...',
    'gateout.success': 'Vehicle successfully gated out.',
    'gateout.emptyTitle': 'No Vehicles to Exit',
    'gateout.emptyDesc': 'There are no vehicles currently in Checked-In or Gated-In status.',
    'gateout.active': 'Active',
    'gateout.location': 'Current Location',
    'gateout.timeInYard': 'Total Time in Yard',
    'gateout.equipment': 'Equipment',
    'gateout.checkoutBtn': 'Process Exit',

    'res.title': 'Resource Management',
    'res.subtitle': 'Configure docks, yard slots, and operational zones.',
    'res.modeEnter': 'Enter Edit Mode',
    'res.modeExit': 'Exit Edit Mode',
    'res.addDock': 'Add Dock',
    'res.addSlot': 'Add Yard Slot',
    'res.docks': 'Dock Doors',
    'res.slots': 'Yard Slots',
    'res.reset': 'Force Reset',
    'res.capabilities': 'Capabilities',
    'res.universal': 'Universal Access',
    'res.configure': 'Configure',
    'res.modalEdit': 'Edit',
    'res.modalNew': 'New',
    'res.modalSubtitle': 'Configure resource properties and constraints.',
    'res.identifier': 'Resource Identifier',
    'res.defaultStatus': 'Default Status',
    'res.statusAvail': 'Available',
    'res.statusUnavail': 'Unavailable (Maintenance)',
    'res.equipTypes': 'Allowed Equipment Types',
    'res.apply': 'Apply Changes',
    'res.deploy': 'Deploy Resource',

    'drv.title': 'Driver Registry',
    'drv.subtitle': 'Manage authorized drivers and carriers.',
    'drv.add': 'Add Driver',
    'drv.statusOn': 'On Site',
    'drv.statusAway': 'Away',
    'drv.license': 'License #',
    'drv.edit': 'Edit Driver',
    'drv.fullName': 'Full Name',

    'settings.title': 'System Settings',
    'settings.subtitle': 'Global configuration and preferences.',
    'settings.general': 'General Configuration',
    'settings.yardName': 'Yard Name',
    'settings.language': 'Language',
    'settings.darkMode': 'Dark Mode',
    'settings.thresholds': 'Operational Thresholds',
    'settings.yardThresh': 'Yard Dwell Alert (Hrs)',
    'settings.dockThresh': 'Dock Dwell Alert (Hrs)',
    'settings.storage': 'Data & Storage',
    'settings.danger': 'Danger Zone',
    'settings.reset': 'Factory Reset',
    'settings.resetBtn': 'Delete All Data',
    'settings.workingHours': 'Facility Working Hours',
    'settings.shifts': 'Shifts',
    'settings.addShift': 'Add Shift',
    'settings.closed': 'Facility Closed',
    'settings.whatsapp': 'WhatsApp Integration',
    'settings.waDesc': 'Enable automated alerts to admin staff via WhatsApp.',
    'settings.waInput': 'Recipient Number (with Country Code)',
    'settings.waAdd': 'Add Recipient',

    'tt.title': 'Trailer Types',
    'tt.subtitle': 'Define equipment categories and service times.',
    'tt.add': 'Add Type',
    'tt.defaultDuration': 'min default',
    'tt.processTime': 'min / pallet',
    'tt.modalTitle': 'Trailer Type',
    'tt.typeName': 'Type Name',
    'tt.defServiceTime': 'Default Service Time (Minutes)',
    'tt.multiplesHint': 'Used for initial schedule blocks.',
    'tt.palletHint': 'If set, duration = pallet count * this value.',

    'cal.title': 'Appointment Calendar',
    'cal.closed': 'Closed',
    'cal.closedMsg': 'The facility is closed on this day. Check settings to configure working hours.',
    'cal.resource': 'Resource',

    'car.title': 'Carriers',
    'car.subtitle': 'Manage transport partners.',
    'car.add': 'Add Carrier',
    'car.noContact': 'No contact info',
    'car.modalTitle': 'Carrier',
    'car.name': 'Company Name',
    'car.email': 'Email',
    'car.phone': 'Phone',

    'log.title': 'Trailer Management',
    'log.subtitle': 'Complete history and status of all trailers.',
    'log.add': 'Register Trailer',
    'log.searchPlaceholder': 'Search trailer, driver, or ID...',
    'log.statusAll': 'All Statuses',
    'log.statusSch': 'Scheduled',
    'log.statusInYard': 'In Yard',
    'log.statusIn': 'At Dock',
    'log.statusOut': 'Completed/Gone',
    'log.typeAll': 'All Types',
    'log.empty': 'No records found matching filters.',
    'log.expired': 'Expired',
    'log.days': 'days left',
    'log.inYard': 'In Yard',
    'log.moveToYard': 'Move to Yard',
    'log.eway': 'E-Way Bill',
    'log.checkIn': 'Check In',
    'log.selectSlot': 'Select Yard Slot',
    'log.confirmMove': 'Confirm Move',

    'guard.title': 'Guard Gate',
    'guard.subtitle': 'Entry and Exit Processing',
    'guard.induct': 'Gate In',
    'guard.exodus': 'Gate Out',
    'guard.scan': 'Scan / Entry',
    'guard.trailerNum': 'Trailer Number',
    'guard.carrier': 'Carrier',
    'guard.selectCarrier': 'Select Carrier',
    'guard.driverName': 'Driver Name',
    'guard.driverLicense': 'License Number',
    'guard.driverPhone': 'Phone Number',
    'guard.ewayBillNum': 'E-Way Bill #',
    'guard.ewayBillExp': 'E-Way Bill Expiry',
    'guard.gateInBtn': 'Gate In',
    'guard.onPremise': 'Recent Arrivals',
    'guard.gateOutBtn': 'Gate Out',
    'guard.successIn': 'Success! Trailer gated in.',
    'guard.successOut': 'Success! Trailer gated out.',
  },
  hi: {
    'dash.title': 'स्विफ्टयार्ड डैशबोर्ड',
    'dash.subtitle': 'वास्तविक समय यार्ड अवलोकन और संसाधन ट्रैकिंग।',
    'dash.live': 'लाइव सिस्टम',
    'kpi.pending': 'लंबित नियुक्तियाँ',
    'kpi.occupied': 'अधिकृत डॉक्स',
    'kpi.yard': 'यार्ड में ट्रेलर्स',
    'kpi.occupancy': 'अधिभोग दर',
    'dash.docks': 'डॉक दरवाजे',
    'dash.slots': 'यार्ड स्लॉट',
    'dash.distribution': 'डॉक स्थिति वितरण',
    'dash.total': 'कुल डॉक',
    'dash.efficiency': 'परिचालन दक्षता',
    'dash.gateToDock': 'गेट से डॉक तक का औसत समय',
    'dash.dockDwell': 'डॉक पर औसत समय',
    'dash.yardDwell': 'यार्ड में औसत समय',
    'dash.longStay': 'लंबे समय से रुके ट्रेलर्स',
    'dash.mins': 'मिनट',
    'dash.alert': 'चेतावनी',
    'dash.alertMsg': 'संसाधन अनुपलब्ध',
    'dash.congestion': 'भीड़भाड़ निगरानी',

    'nav.dashboard': 'कमांड सेंटर',
    'nav.driver-board': 'लाइव बोर्ड',
    'nav.guard-gate': 'गार्ड गेट',
    'nav.calendar': 'नियुक्ति कैलेंडर',
    'nav.schedule': 'नियुक्तियाँ',
    'nav.gatehouse': 'चेक-इन/आउट',
    'nav.gateout': 'चेक-आउट',
    'nav.resources': 'संसाधन',
    'nav.carriers': 'कैरियर्स',
    'nav.trailers': 'ट्रेलर्स',
    'nav.trailer-types': 'ट्रेलर प्रकार',
    'nav.drivers': 'ड्राइवर',
    'nav.settings': 'सेटिंग्स',
    'nav.help': 'सहायता और दस्तावेज़',

    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.add': 'जोड़ें',
    'common.status': 'स्थिति',
    'common.id': 'आईडी',
  }
};
